### PR TITLE
Allow for individual hue and lightness settings for the three corners

### PR DESCRIPTION
**Pull request by romanseidl**
The changes allow to set the hue and the lightness 
  - as a scalar (same as before, giving the first corner or the lightness for all corners) or 
  - as vectors defining the hues and/or the lightness separately for each corner

Example: 

      Tricolore(full_data, p1 = 'sa', p2 = 'sb', p3 = 'sc', legend = T,
               center = c, spread = true_scale, show_data = F,
               contrast = 0.2, lightness = c(0.5,1.0,0.5), chroma = 1, hue = c(0.028, 0.361, 0.694))

I tested it and it worked fine, even though it is safe to say that using hues to far from the 120 degrees offset produces not so nice results. But still it allows to tweak the colours nicely, even more so with the lightness.

### CODE REVIEW

**Comment by romanseidl** [comment]
I will have to have a look at those tests. Should I write some to cover the new functionalities?

**Comment by romanseidl** [comment]
Hm, that's the NA handling I suppose this was not correct according to the tests already before? Or am I wrong?

**Comment by jschoeley** [comment]
Thank you Roman. Could you please state your motivation and use-cases for the proposed addition.

**Comment by romanseidl** [comment]
We wanted to have clearer colors for the three corners as we were not satified with what we would get from the 120 degrees and even more so the equal lightness. It is e.g. impossible to e.g.:

- have a red and a yellow at the same time as they are 60 but not 120 degrees apart
- have a strong red and a clear green as a strong red has to be darker than green

This is a very simple means to allow for more flexible colour shemes.

**Comment by jschoeley** [comment]
Thanks again Roman but I've decided not to include this feature in tricolore.

tricolore is designed to be flexible within the constraints of 2 principles which help explaining and interpreting the color scale:

1. Lightness and chroma encode the distance of a composition from the center with the center being a perfect grey and the darkest color among all.
2. Hue encodes the direction of deviation from the center.

Allowing unequally spaced hues and unequal lightness values shifts the grey-point and the darkest point of the color-scale away from the center, thereby violating 1.

While beautiful color maps can be designed with the added flexibility, they lack a clear neutral point at the center as illustrated below.

rplot

**Comment by romanseidl** [comment]
Thanks for testing it, I was not aware of the "centre" issue, I will have a look if I also had that. 

Anyway, I would like to reproduce your example, could you send me the code?

**Comment by jschoeley** [comment]
Foolishly I didn't save it. I remember installing your patched version of tricolore and reproducing the education levels example from the Readme. I then changed hue and lightness values for each of the three proportions so that I get yellow, blue and red colors, don't remember the values though... The shifting of the greypoint and darkpoint off-center when using unequally spaced hues or unequal lightness levels is a mathematical consequence of the color-space and the way I mix colors in it. See Appendix A of https://www.demographic-research.org/volumes/vol36/21/36-21.pdf for details.

**Pull request closed without merging**
